name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      env:
        DOCKER_HUB_USERNAME: veitveit
        # DOCKER_HUB_PASSWORD should be set in GitHub repository secrets

    - name: Build and push Docker image
      run: |
        if [[ $GITHUB_REF == refs/tags/release-* ]]; then
          IMAGE_NAME=veitveit/vsclust:${GITHUB_REF#refs/tags/}
        else
          IMAGE_NAME=veitveit/vsclust:latest
        fi
        docker build -t $IMAGE_NAME -f inst/docker/Dockerfile .
        docker push $IMAGE_NAME
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
